config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bank_accounts
  resources :transfers
  resources :users
  root 'bank_accounts#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Banking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body> 
  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand">BANKING</span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Home', '/' %></li> 
            <li><%= link_to 'New Transfer', new_transfer_path %></li>
          </ul>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                  <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  </li>
              <% end %>
            </ul>
           </div>
        </div>
      </div>
    </nav>
    <div class="container theme-showcase" role="main">
      <%= yield %>
    </div>
</body>
</html>